name: Deploy Blazor WASM to GitHub Pages

on:
  push:
    branches: [ "main" ] 

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x   

    - name: Restore
      run: dotnet restore

    - name: Publish
      run: dotnet publish -c Release -o release

    - name: Change base href
      run: sed -i 's/<base href="\/" \/>/<base href="\/FootballTracker\/" \/>/' release/wwwroot/index.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: release/wwwroot
